[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn deploy-build"
publish = ".next"

[build.environment]
NETLIFY_AUTH_TOKEN = "nfp_XLL4SL7iWV1a9QF9esk3s7b3UPgbQdXc972a"
NETLIFY_SITE_ID = "d9fc208e-6aa2-490a-8c1c-bdddde3e77ee"
 

