fragment BlockSettings on PageBuilderDynamicBlocksBlockSettings {
  spacing {
    mobile {
      top
      bottom
    }
    desktop {
      top
      bottom
    }
  }
  visibility {
    showOnMobile
    showOnDesktop
  }
}
