fragment blogsBlock on PageBuilderDynamicBlocksBlogs {
  fieldGroupName
  tittle
  ctaBlocks {
    title
    ctaButton {
      fieldGroupName

      text
      link {
        ...AcfLink
      }
    }
    contactInfo
  }
}
