fragment blogsBlock on PageBuilderDynamicBlocksBlogs {
  fieldGroupName
  tittle
  ctaBlocks {
    ctaButton {
      fieldGroupName
      text
      link {
        nodes {
          slug
          uri
        }
      }
    }
    contactInfo
  }
}
