fragment blogsBlock on PageBuilderDynamicBlocksBlogs {
  fieldGroupName
  tittle
  ctaBlocks {
    title
    ctaButton {
      fieldGroupName

      text
      link {
        nodes {
          slug
          uri
        }
      }
    }
    contactInfo
  }
}
