fragment CardsBlock on PageBuilderDynamicBlocksCardsBlockLayout_Fields {
  __typename
  title
  cards {
    title
    description
    hasImage
    iconImage {
      node {
        sourceUrl
      }
    }
    backgroundColor
    link {
      ...AcfLink
    }
  }
  blockSettings {
    ...BlockSettings
  }
}
