fragment CareerBlock on PageBuilderDynamicBlocksCareersBlockLayout_Fields {
  description
  fieldGroupName
  title
  noJobVacancy
  careers {
    careerDescription
    location
    title

    cta {
      ...AcfLink
    }
  }
}
