fragment CareerBlock on PageBuilderDynamicBlocksCareersBlock {
  description
  fieldGroupName
  title

  careers {
    careerDescription
    location
    title
    cta {
      ctaText
      ctaLink {
        url
        target
      }
    }
  }
}
