fragment Certifications on PageBuilderDynamicBlocksCertificationsLayout {
  __typename
  certification {
      preview {
        node {
          sourceUrl
        }
      }
      document {
        node {
          mediaItemUrl
        }
      }
      certificationName
      description
  }
}
