fragment ChecklistBlock on PageBuilderDynamicBlocksChecklistBlockLayout_Fields {
  fieldGroupName
  header
  preHeader
  ctaGroup {
    ctaText

    link {
      ...AcfLink
    }
  }
  checklist {
    item
  }
}
