fragment CompanyHistory on PageBuilderDynamicBlocksCompanyHistoryBlockLayout_Fields {
  fieldGroupName
  title

  blockSettings {
    ...BlockSettings
  }
  histories {
    description
    year

    mainImage {
      node {
        sourceUrl
      }
    }
  }
}
