fragment CompanyHistory on PageBuilderDynamicBlocksCompanyHistoryBlockLayout_Fields {
  fieldGroupName
  title
  histories {
    description
    year

    supportingImage {
      node {
        sourceUrl
      }
    }
    mainImage {
      node {
        sourceUrl
      }
    }
  }
}
