fragment CompanyHistory on PageBuilderDynamicBlocksCompanyHistoryBlock {
  fieldGroupName
  title
  histories {
    description
    year
    mainImage {
      node {
        sourceUrl
      }
    }
  }
}
