fragment CTABannerBlock on PageBuilderDynamicBlocksCtaBannerBlockLayout {
  bgColor
  fieldGroupName
  cta {
    ctaText
    link {
      target
      title
      url
    }
  }
  title
  bannerImage {
    node {
      sourceUrl
    }
  }
}
