fragment Form on PageBuilderDynamicBlocksFormLayout {
  fieldGroupName
  form {
    copyrightText
    formTitle
  }
  contacts {
    contactInformation {
      title
      email
      fieldGroupName
      phoneNumber {
        url
        title
      }
      location {
        locationInformation
        fieldGroupName
        locationLink {
          url
          target
          title
        }
      }
    }
  }
}
