fragment FormBlock on PageBuilderDynamicBlocksFormLayout_Fields {
  fieldGroupName
  form {
    copyrightText
    formTitle
  }
  contactInformation {
    email
    fieldGroupName
    phoneNumber
    location {
      locationInformation
      fieldGroupName
      locationLink {
        url
        target
        title
      }
    }
  }
}
