fragment Form on PageBuilderDynamicBlocksFormLayout {
  fieldGroupName
  form {
    copyrightText
    formTitle
  }
  contacts {
    contactInformation {
      email
      fieldGroupName
      phoneNumber
      location {
        locationInformation
        fieldGroupName
        locationLink {
          url
          target
          title
        }
      }
    }
  }
}
