fragment GalleryBlock on PageBuilderDynamicBlocksGalleryBlockLayout_Fields {
  fieldGroupName
  title
  reverseLayout
  gallery {
    imageTitle

    galleryImage {
      node {
        ...MediaItem
      }
    }
    textOrImge
    text {
      content
      title
    }
  }
}
