fragment GalleryBlock on PageBuilderDynamicBlocksGalleryBlock {
  fieldGroupName
  title
  reverseLayout
  gallery {
    imageTitle

    galleryImage {
      node {
        sourceUrl
      }
    }
    textOrImge
    richText
  }
}
