fragment HeroBlock on PageBuilderDynamicBlocksHeroBlockLayout_Fields {
  title
  backgroundImage{
    node{
      ...MediaItem
    }
  }
  description
  button {
    ...AcfLink
  }
  blockSettings {
    ...BlockSettings
  }
}
