fragment IconsBlock on PageBuilderDynamicBlocksIconsBlockLayout_Fields {
  description
  header
  preHeader
  fieldGroupName
  ctaLink {
    ctaText
    ctaLink {
      ...AcfLink
    }
  }
  icons {
    iconDescription
    iconTitle
    iconImage {
      node {
        sourceUrl
      }
    }
  }
}
