fragment ImageContent on PageBuilderDynamicBlocksImageContent {
  fieldGroupName
  reverse
  image {
    node {
      sourceUrl
    }
  }
  content {
    description
    icons {
      text
      icon {
        node {
          sourceUrl
        }
      }
    }
    title
  }
}
