fragment ImageContent on PageBuilderDynamicBlocksImageContentLayout_Fields {
  fieldGroupName
  reverse
  image {
    node {
      sourceUrl
    }
  }
  contentGroup {
    description
    icons {
      text
      icon {
        node {
          sourceUrl
        }
      }
    }
    title
  }
}
