fragment PageBuilder on PageBuilder {
  dynamicBlocks {
    ...HeroBlock
    ...CardsBlock
    ...Team_Block
    ...Service_block

    ...TitleTextBlock
    ...TitleBlock
    ...PageBanner
    ...ImageBlock
    ...ImageTextBlock
    ...CompanyHistory
    ...GalleryBlock
    ...IconsBlock
    ...VideoBlock
    ...CareerBlock
    ...ChecklistBlock
    ...CTABannerBlock
    ...ImageContent
    ...CenterTitleText
    ...FormBlock
  }
}
