fragment PostFragment on Post {
  author {
    node {
      avatar {
        url
      }
      name
      registeredDate
    }
  }
  dateGmt
  featuredImage {
    node {
      sourceUrl
    }
  }
  content
  title
  slug
  uri
  DELang: translation(language: DE) {
    uri
  }
  ENLang: translation(language: EN) {
    uri
  }
  pagesSetting {
    ...pagesSetting
  }
}
