fragment PostFragment on Post {
  databaseId
  author {
    node {
      avatar {
        url
      }
      name
      registeredDate
    }
  }
  dateGmt
  featuredImage {
    node {
      ...MediaItem
    }
  }
  language {
    code
  }
  content
  title
  link
  slug
  uri
  DELang: translation(language: DE) {
    link
  }
  ENLang: translation(language: EN) {
    link
  }
  pagesSetting {
    ...pagesSetting
  }
}
