fragment Service_block on PageBuilderDynamicBlocksServiceBlockLayout_Fields {
  fieldGroupName
  services {
    title
    description
    featuredImage {
      node {
        sourceUrl
      }
    }
    link {
      ...AcfLink
    }
  }
}
