fragment TitleTextBlock on PageBuilderDynamicBlocksTitleTextBlockLayout_Fields {
  fieldGroupName
  title
  haveShape

  content {
    contents {
      text
      fieldGroupName
    }
    contentTitle
  }
  cta {
    ctaText
    link {
      url
    }
  }
}
